/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : fsl_sdhc1.c
**     Project     : FreeRTOS-lwIP-IoT
**     Processor   : MK64FN1M0VLL12
**     Component   : fsl_sdhc
**     Version     : Component 1.3.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-11-02, 18:48, # CodeGen: 19
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file fsl_sdhc1.c
** @version 01.00
*/         
/*!
**  @addtogroup fsl_sdhc1_module fsl_sdhc1 module documentation
**  @{
*/         

/* fsl_sdhc1. */

#include "Events.h"
#include "fsl_sdhc1.h"
sdhc_host_t fsl_sdhc1_host;

void fsl_sdhc1_IRQHandler(void)
{
#if defined BSP_FSL_SDHC_USING_IRQ
  SDHC_DRV_DoIrq(fsl_sdhc1_IDX);
#endif
}
const sdhc_user_config_t fsl_sdhc1_InitConfig0 = {
  .clock = 400000U,
  .transMode = kSdhcTransModeAdma2,
  .cdType = kSdhcCardDetectGpio,
  .cardDetectCallback = fsl_sdhc1_OnCardDetect0,
  .cardIntCallback = fsl_sdhc1_OnCardInterrupt0,
  .blockGapCallback = fsl_sdhc1_OnCardBlockGap0,
};


/* END fsl_sdhc1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
